version: "3.9"
services:
    mongo_docker:
        image: mongo:latest
        ports:
            - "27019:27017"
        volumes:
            - /d/DOCKER/MONGO/db_data:/data/db
        networks:
            - backend_network

networks:
    backend_network:
        driver: bridge
